package com.roycemars.royalgame.core.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFFFDD0B)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFFFFDD0B)
val onPrimaryContainerLight = Color(0xFF000000)
val secondaryLight = Color(0xFFFF107B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF107B)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF550F72)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF550F72)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF16101E)
val errorLight = Color(0xFFFF107B)
val onErrorLight = Color(0xFFFFFFFF)

val primaryDark = Color(0xFFFFDD0B)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFFFDD0B)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFFF107B)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFFFF107B)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFF550F72)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF550F72)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF16101E)
val onSurfaceDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFF107B)
val onErrorDark = Color(0xFFFFFFFF)

val backgroundGradientLight = Color(0xFF550F72)
val backgroundGradientDark = Color(0xFF16101E)
